# Generated by Django 5.0.6 on 2024-07-07 06:55

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(default=2, max_length=10, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.CharField(default=account.models.generate_unique_username, max_length=8, primary_key=True, serialize=False),
        ),
    ]
