# Generated by Django 5.0.6 on 2024-07-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_first_name_alter_useraccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
    ]
