# Generated by Django 5.0.6 on 2024-07-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_last_name_alter_useraccount_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
