# Generated by Django 5.0.7 on 2024-08-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_chat_room_message_chatroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='participants',
        ),
    ]
