# Generated by Django 5.0.7 on 2024-08-20 12:46

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_group_user_group_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, default=chat.models.get_group_image, max_length=255, null=True, upload_to=chat.models.get_group_image_filepath),
        ),
    ]
