# Generated by Django 5.0.7 on 2024-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_group_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
