# Generated by Django 5.0.7 on 2024-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
