# Generated by Django 5.0.6 on 2024-07-30 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.datetime(2024, 7, 30, 14, 54, 30, 536836, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
