# Generated by Django 5.0.6 on 2024-08-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0006_alter_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
