# Generated by Django 5.0.7 on 2024-08-03 08:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0007_alter_friendrequest_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request_notification', 'Friend Request Notfication'), ('regular_notification', 'Regular Notfication')], default=datetime.datetime(2024, 8, 3, 8, 6, 12, 562157, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
